
INSERT INTO USUARIO (ID,NOME,CPF,LOGIN,SENHA) VALUES (1,'Luiz Gabriel','123','login','j1+Fsg/B7OH/5W1+lbAGLg==');
INSERT INTO ESPECIALIDADE (ID,NOME) VALUES (1,'Emergência');
INSERT INTO HISTORICO_MEDICO (ID,COD_USUARIO,COD_ESPECIALIDADE,DESCRICAO,DATA) VALUES (1,1,1,'string','2016-07-27 20:01:34');
